### ISSUE TITLE
Does not work on IE 11

### ISSUE THREAD

**Issue by devinus** [anonyco/FastestSmallestTextEncoderDecoder#2]
IE 11 doesn't support `Uint8Array.prototype.slice`.

**Comment by anonyco** [comment]
Ooops... I switched up the sides of a very important ternary expression. Now, the ternary expression has been fixed with [this commit](https://github.com/anonyco/FastestSmallestTextEncoderDecoder/commit/38756de7851702056ae2b85a6dd7cd33620fb7e3). I then minified the changes files, performed some tests, and uploaded the changes to Dropbox and npm. Any of your existing projects which are using the Dropbox links should be receiving the bug fixes.

Thank you so much for opening this issue. I really appreciate it when someone takes the time to identify a bug, track it down, and open an Issue to shed light upon it. Thank you.
