### ISSUE TITLE
Consider publishing the individual files to npm

### ISSUE THREAD

**Issue by devinus** [anonyco/FastestSmallestTextEncoderDecoder#3]
This would make tree-shaking in Webpack not include the same amalgamated file twice when used in ProvidePlugin.

**Comment by anonyco** [comment]
Thank you so much for opening this pressing issue. I'm sorry, but I am not certain about what you are referring to when you say "individual." Are you referring to the [individual folder](https://github.com/anonyco/FastestSmallestTextEncoderDecoder/tree/master/individual) or a specific series of files? Also, if the latter, then which files?

Again, I *really* appreciate it when someone takes the time to identify a bug, track it down, and open an Issue to shed light upon it. Thank you.

**Comment by anonyco** [comment]
Success (I think)! I have pushed up a new version of the library to integrate an [ES6 module](https://2ality.com/2017/04/setting-up-multi-platform-packages.html#module%3A-native-features%2C-esm) alternative to the library because it appears as though ES6 modules are easier for webpack to swallow (please don't quote me on this--I just learned webpack today, so I do not know much about webpack). 

Below is a download link for a "poor-man's" test used to validate whether or not the library is compatible with webpack. After opening the console on the *demo.html* page and refreshing, the number `15` appeared in the console and no errors were reported. Thus, I assume that my changes have fixed the issues with webpack. I realize that this is not a very good benchmark, but I am at a loss to find any better way to test this library's compatibility with webpack.

As I am still very new and inexperienced with ES6 modules and webpack, I would really appreciate your inspection and critique of my work in order to verify that everything has been done correctly with best-practices and so forth. Thank you so much for bringing this issue to my attention and explaining the problem so clearly and concisely. I really appreciate that you have spent your time to contribute to this project.

~ Happy coding!

<br />

[Download my "poor-man's" webpack test](https://github.com/anonyco/FastestSmallestTextEncoderDecoder/files/3710108/TestingEncoderDecoder.zip)
