### ISSUE TITLE
[Feature Request]Add support for encodeInto

### ISSUE THREAD

**Issue by Bnaya** [anonyco/FastestSmallestTextEncoderDecoder#7]
https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encodeInto

Thanks :)

**Comment by anonyco** [comment]
I shall begin work on a new flavour of `FastestSmallestTextEncoderDecoder` which includes this method. Thank you for bringing this to my attention. The problem with adding this method onto the existing flavours is that it will bloat the size.

~ Happy Coding and merry Christmas, Hanukkah, Kwanzaa, or Three Kings (whatever is your favorite flavour of ice cream)!

**Comment by anonyco** [comment]
This new update is taking so long because it is coming with some important upgrades:

* A new `encodeInto` flavour
* A new npm repository for the encodeInto branch
* NodeJS compliance test scripts
* Install helper scripts for Unix and Windows
* Minor performance and size improvements
* Performance benchmarks
* Better ES6 module support

**Comment by anonyco** [comment]
Thank you so much for your patience over the course of the past several months. They have been very busy for me. Thankfully, I have a lot more time to myself for working on projects like this now.
