### ISSUE TITLE
Caveat for angular projects

### ISSUE THREAD

**Issue by biltongza** [anonyco/FastestSmallestTextEncoderDecoder#9]
We are using this library as a polyfill for IE11 which appears to not have TextEncoder defined.
We are using Angular 8.

I previously had version 1.0.8 installed, and in my `polyfills.ts` I had `import 'fastestsmallesttextencoderdecoder';` and all was well in Chrome and Firefox, but IE11 had a problem with that, with `TextEncoder` being undefined.

After updating to 1.0.14 and making no other changes, I was getting errors from the library that `f.decode` is undefined. I think it had to do with the _version_ of the library that was being loaded in the browser, it appeared to either be incompatible with Chrome/Firefox or the build process was using the wrong file (perhaps it was using the node file in the browser?).

After changing my import to specifically target the browser version, i.e. `import 'fastestsmallesttextencoderdecoder/EncoderDecoderTogether.min';` in my `polyfills.ts`, all is well AND IE11 is now working just fine.

**Comment by anonyco** [comment]
I apologize for taking so long to respond to you. As I myself do not use AngularJS, I researched the topic of incorporating AngularJS support into this library. However, I found no solution which did not add many files to the top level directory, so all the solutions I found would severely cluttered this project. If you can direct me to an appropriate guide which would not junk up the the top level directory, I would be happy to invest as much more time as is needed to incorporate AngularJS. Otherwise, I would suggest using the dropbox script from the [Quick Start](https://github.com/anonyco/FastestSmallestTextEncoderDecoder#quick-start) section. I hope this helps.

~ Happy Coding!

**Comment by rhlin** [comment]
I am also angular user, using angular 9. I used version 1.0.14, and imported it by inserting ` import 'fastestsmallesttextencoderdecoder'; ` in `polyfills.ts.

It works in IE 11,  with es5 version  which is specified by `main` property of `package.json`.
But it failed in Chrome, reporting error :

``` 
Uncaught TypeError: F.decode is not a constructor
    at Module../node_modules/fastestsmallesttextencoderdecoder/NodeJS/EncoderAndDecoderNodeJS.min.module.js (EncoderAndDecoderNodeJS.min.module.js:5)
    at __webpack_require__ (bootstrap:84)
    at Module../src/polyfills.ts (polyfills.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Object.1 (polyfills.ts:103)
    at __webpack_require__ (bootstrap:84)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at polyfills.js:1
```

I tracked it down, and found that it ran with es2015 version (aka, the module version) in Chrome.
And I did some test, t**he `EncoderAndDecoderNodeJS.src.module.js` source code can not directly run in Chrome.** 

It seems there are some errors in [line 112 of  file `FastestSmallestTextEncoderDecoder/NodeJS/EncoderAndDecoderNodeJS.src.module.js`](https://github.com/anonyco/FastestSmallestTextEncoderDecoder/blob/6b8b6eed5c900560f09b534ff22556584d6e1246/NodeJS/EncoderAndDecoderNodeJS.src.module.js#L112)

When `window_global["TextDecoder"]` exists,  `new FinalTextDecoder["decode"]`  failed in Chrome since decode is not a constructor.  And I tried  `new FinalTextDecoder()["decode"]` , it works.
Line 113 has the same issue without function call parentheses **()**

Expecting new release to fix this, thank you~

**Comment by anonyco** [comment]
I have updated the instructions for AngularJS: [https://github.com/anonyco/FastestSmallestTextEncoderDecoder/blob/master/README.md#angularjs](https://github.com/anonyco/FastestSmallestTextEncoderDecoder/blob/master/README.md#angularjs). As AngularJs is still foreign to me, please check my terminology and sentence structure. Did I do a correct job at explaining what needs to be done for AngularJS and/or what should I change? 

As for the [EncoderAndDecoderNodeJS.src.module.js](https://github.com/anonyco/FastestSmallestTextEncoderDecoder/blob/6b8b6eed5c900560f09b534ff22556584d6e1246/NodeJS/EncoderAndDecoderNodeJS.src.module.js#L112) file, it is not meant to be runned directly. Using that source file directly results in errors. Rather, I was forced to make that file the way it is in order to get a valid minified file via Closure Compiler. After the source file is minified with Closure Compiler, additional steps are taken to transform it into a working ES6 module. I should really put in a note about that.

Many thanks and happy coding.

**Comment by anonyco** [comment]
I am going to close this issue for now. If you feel it needs to be reopened, please feel free to do so. Again, many thanks.
